CREATE TABLE demo.SALES_DETAIL
(
    SALES_DATE_TIME DATETIME NOT NULL COMMENT '売上日時',
    ITEM_CODE VARCHAR(13) NOT NULL COMMENT '商品コード',
    AMOUNT INT NOT NULL COMMENT '数量',
    PRIMARY KEY(SALES_DATE_TIME, ITEM_CODE)
) COMMENT = '売上明細';

CREATE TABLE demo.ITEM_INFO
(
    ITEM_CODE VARCHAR(13) NOT NULL COMMENT '商品コード',
    ITEM_NAME VARCHAR(128) COMMENT '商品名',
    CATEGORY_CODE CHAR(4) NOT NULL COMMENT 'カテゴリーコード',
    CATEGORY_NAME VARCHAR(128) COMMENT 'カテゴリー名',
    UNIT_PRICE INT NOT NULL COMMENT '単価',
    REGISTERED_DATE DATE NOT NULL COMMENT 'マスタ登録日',
    BEGIN_DATE DATE NOT NULL COMMENT 'マスタ適用開始日',
    END_DATE DATE NOT NULL COMMENT 'マスタ適用終了日',
    PRIMARY KEY(ITEM_CODE, BEGIN_DATE)
) COMMENT = '商品マスタ';

CREATE TABLE demo.CATEGORY_SUMMARY
(
    CATEGORY_CODE CHAR(4) NOT NULL COMMENT 'カテゴリーコード',
    CATEGORY_NAME VARCHAR(128) COMMENT 'カテゴリー名',
    AMOUNT INT NOT NULL COMMENT '数量',
    SELLING_PRICE INT NOT NULL COMMENT '売上金額'
) COMMENT = 'カテゴリ別売上集計';